name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
        run: npm i
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run export
          wait-on: "http://localhost:3000"
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
